// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolveChess.DAL.Model;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SolveChess.DAL.Model.GameModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BlackSideUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("CastlingRightBlackKingSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CastlingRightBlackQueenSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CastlingRightWhiteKingSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CastlingRightWhiteQueenSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EnpassantSquareFile")
                        .HasColumnType("int");

                    b.Property<int?>("EnpassantSquareRank")
                        .HasColumnType("int");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FullMoveNumber")
                        .HasColumnType("int");

                    b.Property<int>("HalfMoveClock")
                        .HasColumnType("int");

                    b.Property<int>("SideToMove")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("WhiteSideUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SolveChess.DAL.Model.MoveModel", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<string>("Notation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GameId", "Number", "Side");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("SolveChess.DAL.Model.MoveModel", b =>
                {
                    b.HasOne("SolveChess.DAL.Model.GameModel", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
